In [1]:
import pandas as pd
import glob

In [2]:
a=["CordAscent","LambdaMART","LambdaRank","LinearReg","ListNet","MART","RandomFor","RankBoost","RankNet"]
b=[
"./chart1_data.csv",
"./chart2_data.csv",
"./chart3_data.csv",
"./chart4_data.csv",
"./chart5_data.csv",
"./chart6_data.csv",
"./chart7_data.csv",
"./chart8_data.csv",
"./chart9_data.csv",
]

In [3]:
temp=[]
for i in range(9):   
    try:
        df=pd.read_csv(b[i],index_col=0)
        df['model']=a[i]
        temp.append(df)
    except:
        print(i)

4

In [4]:
merged=pd.concat(temp);

E:\00_Installed_programs\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

# Remove extra columns

In [5]:
import pandas as pd
import glob

In [6]:
for j in merged.columns:
    if "feature_rank" not in j and "1-qid" not in j and "model" not in j:
        merged.drop(j,axis=1,inplace=True)

In [7]:
merged

,1-qid,C_CE_I_R_feature_rank,Change_in_Net_Assets_feature_rank,Current_Liabilities_feature_rank,NonCurrent_Liabilities_feature_rank,NonCurrent_Liability_feature_rank,Personal_income_feature_rank,Population_feature_rank,Primary_gov_debt_feature_rank,Restricted_Net_Assets_feature_rank,...,lt_percapita_feature_rank,model,net_asst_ratio_feature_rank,op_ratio_feature_rank,opeb_income_ratio_feature_rank,pension_income_ratio_feature_rank,quick_ratio_feature_rank,rev_income_ratio_feature_rank,surplus_percap_feature_rank,tax_income_ratio_feature_rank
0,2006,27,20,24,1,12,5,16,4,13,...,11,CordAscent,28,6,32,19,18,9,3,17
1,2006,9,19,10,2,21,6,23,5,22,...,28,CordAscent,26,11,29,17,16,27,4,20
2,2006,33,26,19,1,9,10,16,6,32,...,15,CordAscent,30,4,7,23,17,14,3,13
3,2006,24,33,10,1,32,5,25,20,14,...,13,CordAscent,19,15,23,9,18,31,2,28
4,2006,32,22,19,1,12,6,9,4,24,...,33,CordAscent,21,27,30,13,20,29,23,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,2016,12,29,17,15,23,5,2,28,9,...,22,RankNet,19,24,30,13,31,6,14,8
546,2016,4,21,2,9,14,15,7,12,6,...,18,RankNet,25,33,24,30,29,32,28,22
547,2016,10,29,7,18,27,17,3,11,13,...,9,RankNet,19,16,32,1,31,4,33,23
548,2016,2,10,1,18,26,22,19,4,3,...,23,RankNet,33,28,30,12,24,27,31,17
549,2016,2,20,14,18,19,22,7,17,4,...,16,RankNet,25,10,28,3,26,33,27,30

In [8]:
df.columns

Index(['1-qid', 'two_realRank', 'two_realRank2', 'State', 'RankNet', 'C_CE_I',
       'C_CE_I_R', 'Total_Current_Assets', 'Current_Liabilities',
       'NonCurrent_Liabilities',
       ...
       'lt_percapita_feature_rank', 'net_asst_ratio_feature_rank',
       'op_ratio_feature_rank', 'opeb_income_ratio_feature_rank',
       'pension_income_ratio_feature_rank', 'quick_ratio_feature_rank',
       'rev_income_ratio_feature_rank', 'surplus_percap_feature_rank',
       'tax_income_ratio_feature_rank', 'model'],
      dtype='object', length=104)

In [9]:
merged.to_csv('fiscal_rank.csv',index=False)