In [1]:
import pandas as pd
df=pd.read_csv('./CWURlime_rank.csv')
import numpy as np

In [2]:
rank_columns=list(filter(lambda x: "_feature_rank" in x, df.columns))
print(len(rank_columns))

526

In [3]:
rank_columns=list(filter(lambda x: "_rank" in x, df.columns))
print(len(rank_columns))

526

In [4]:
temp_dict={}
for col in rank_columns:
    temp_dict[col]=col.replace("_rank","_feature_rank")

In [5]:
df.rename(columns=temp_dict,inplace=True)
df

,model,UNITID,1-qid,two_realRank2,two_realRank,State,SCH_DEG,PREDDEG,HIGHDEG,CONTROL,...,UNKN_ORIG_YR8_RT_feature_feature_rank,WDRAW_4YR_TRANS_YR6_RT_feature_feature_rank,WDRAW_4YR_TRANS_YR8_RT_feature_feature_rank,WDRAW_DEBT_MDN_feature_feature_rank,WDRAW_DEBT_N_feature_feature_rank,WDRAW_ORIG_YR2_RT_feature_feature_rank,WDRAW_ORIG_YR3_RT_feature_feature_rank,WDRAW_ORIG_YR4_RT_feature_feature_rank,WDRAW_ORIG_YR6_RT_feature_feature_rank,WDRAW_ORIG_YR8_RT_feature_feature_rank
0,MART,166027,2012,2,2,Harvard University,3,3,4,2,...,270.0,298.0,400.0,386.0,272.0,368.0,512.0,121.0,168.0,239.0
1,MART,243744,2012,3,3,Stanford University,3,3,4,2,...,338.0,118.0,470.0,117.0,430.0,98.0,466.0,364.0,103.0,45.0
2,MART,166683,2012,4,4,Massachusetts Institute of Technology,3,3,4,2,...,401.0,53.0,47.0,174.0,253.0,361.0,432.0,193.0,279.0,504.0
3,MART,144050,2012,6,6,University of Chicago,3,3,4,2,...,395.0,333.0,342.0,463.0,380.0,320.0,55.0,224.0,150.0,390.0
4,MART,110635,2012,49,49,University of California-Berkeley,3,3,4,1,...,81.0,172.0,151.0,261.0,479.0,257.0,494.0,63.0,520.0,298.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,RandomFor,137847,2015,690,690,The University of Tampa,3,3,4,2,...,467.0,126.0,155.0,200.0,349.0,266.0,100.0,346.0,498.0,164.0
1012,RandomFor,110583,2015,703,703,California State University-Long Beach,3,3,4,1,...,31.0,518.0,429.0,331.0,415.0,495.0,306.0,366.0,190.0,388.0
1013,RandomFor,115755,2015,714,714,Humboldt State University,3,3,4,1,...,364.0,244.0,186.0,149.0,245.0,184.0,215.0,192.0,361.0,455.0
1014,RandomFor,140951,2015,732,732,Savannah College of Art and Design,3,3,4,2,...,414.0,496.0,159.0,440.0,201.0,298.0,428.0,295.0,255.0,451.0
1015,RandomFor,127741,2015,735,735,University of Northern Colorado,3,3,4,1,...,63.0,134.0,156.0,208.0,506.0,485.0,302.0,483.0,434.0,520.0

In [6]:
df.shape

(1016, 1584)

In [7]:
df.to_csv("CWURlime_rank.csv",index=None)