In [1]:
import os
import pandas as pd

In [2]:
lime_data=pd.read_csv('CWUR_lime.csv')

In [3]:
contribution_columns=list(filter(lambda x: "_contribution" in x, lime_data.columns))
print(len(contribution_columns))

526

In [4]:
lime_data[contribution_columns]=lime_data[contribution_columns].apply(lambda x:round(x,3))

In [5]:
lime_data

,model,UNITID,1-qid,two_realRank2,two_realRank,State,SCH_DEG,PREDDEG,HIGHDEG,CONTROL,...,UNKN_ORIG_YR8_RT_contribution,WDRAW_4YR_TRANS_YR6_RT_contribution,WDRAW_4YR_TRANS_YR8_RT_contribution,WDRAW_DEBT_MDN_contribution,WDRAW_DEBT_N_contribution,WDRAW_ORIG_YR2_RT_contribution,WDRAW_ORIG_YR3_RT_contribution,WDRAW_ORIG_YR4_RT_contribution,WDRAW_ORIG_YR6_RT_contribution,WDRAW_ORIG_YR8_RT_contribution
0,MART,166027,2012,2,2,Harvard University,3,3,4,2,...,1.272,-1.125,-0.549,0.623,1.262,0.724,-0.026,2.407,1.884,1.465
1,MART,243744,2012,3,3,Stanford University,3,3,4,2,...,1.029,2.628,0.277,-2.642,0.530,2.836,-0.306,0.924,-2.797,3.930
2,MART,166683,2012,4,4,Massachusetts Institute of Technology,3,3,4,2,...,0.581,-3.507,3.705,-1.942,-1.409,-0.747,-0.404,-1.731,-1.244,-0.075
3,MART,144050,2012,6,6,University of Chicago,3,3,4,2,...,-0.619,-0.998,0.963,0.318,-0.719,1.076,3.789,-1.661,2.220,-0.631
4,MART,110635,2012,49,49,University of California-Berkeley,3,3,4,1,...,-3.604,-2.325,-2.577,1.694,0.252,-1.722,0.134,-4.051,0.012,-1.417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,RandomFor,137847,2015,690,690,The University of Tampa,3,3,4,2,...,0.021,-0.169,0.154,-0.127,-0.062,0.094,-0.196,-0.063,0.008,-0.150
1012,RandomFor,110583,2015,703,703,California State University-Long Beach,3,3,4,1,...,0.301,-0.003,0.037,0.076,-0.042,0.011,-0.086,-0.062,0.134,-0.054
1013,RandomFor,115755,2015,714,714,Humboldt State University,3,3,4,1,...,0.057,-0.112,0.139,0.158,-0.111,-0.140,-0.125,-0.135,-0.058,-0.024
1014,RandomFor,140951,2015,732,732,Savannah College of Art and Design,3,3,4,2,...,0.038,0.009,-0.152,0.030,-0.123,-0.089,-0.034,-0.090,-0.104,-0.027
1015,RandomFor,127741,2015,735,735,University of Northern Colorado,3,3,4,1,...,-0.240,0.173,-0.160,0.128,0.006,-0.013,-0.091,0.013,-0.030,-0.002

In [6]:
lime_data.to_csv('CWUR_lime.csv',index=None)